
// This file has been generated by the GUI designer. Do not modify.
namespace Mono.Addins.Gui
{
	internal partial class AddinInfoView
	{
		private global::Gtk.EventBox ebox;
		private global::Gtk.VBox vbox6;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox headerBox;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label labelName;
		private global::Gtk.Label labelVersion;
		private global::Gtk.ScrolledWindow scrolledwindow;
		private global::Gtk.EventBox ebox2;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label labelDesc;
		private global::Gtk.EventBox eboxButs;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnInstall;
		private global::Gtk.Button btnUpdate;
		private global::Gtk.Button btnDisable;
		private global::Gtk.Button btnUninstall;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Mono.Addins.Gui.AddinInfoView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Mono.Addins.Gui.AddinInfoView";
			// Container child Mono.Addins.Gui.AddinInfoView.Gtk.Container+ContainerChild
			this.ebox = new global::Gtk.EventBox ();
			this.ebox.Name = "ebox";
			// Container child ebox.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(12));
			// Container child vbox3.Gtk.Box+BoxChild
			this.headerBox = new global::Gtk.HBox ();
			this.headerBox.Name = "headerBox";
			this.headerBox.Spacing = 6;
			// Container child headerBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 3;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.WidthRequest = 250;
			this.labelName.Name = "labelName";
			this.labelName.Xalign = 0F;
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><big>Some Addin</big></b>");
			this.labelName.UseMarkup = true;
			this.labelName.Wrap = true;
			this.vbox4.Add (this.labelName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelVersion = new global::Gtk.Label ();
			this.labelVersion.Name = "labelVersion";
			this.labelVersion.Xalign = 0F;
			this.labelVersion.LabelProp = global::Mono.Unix.Catalog.GetString ("Version 2.6");
			this.vbox4.Add (this.labelVersion);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelVersion]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.headerBox.Add (this.vbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.headerBox [this.vbox4]));
			w3.Position = 0;
			this.vbox3.Add (this.headerBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.headerBox]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow.CanFocus = true;
			this.scrolledwindow.Name = "scrolledwindow";
			this.scrolledwindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child scrolledwindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.ebox2 = new global::Gtk.EventBox ();
			this.ebox2.Name = "ebox2";
			// Container child ebox2.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.labelDesc = new global::Gtk.Label ();
			this.labelDesc.WidthRequest = 250;
			this.labelDesc.Name = "labelDesc";
			this.labelDesc.Xalign = 0F;
			this.labelDesc.LabelProp = global::Mono.Unix.Catalog.GetString ("Long description of the add-in. Long description of the add-in. Long description of the add-in. Long description of the add-in. Long description of the add-in. Long description of the add-in. ");
			this.labelDesc.Wrap = true;
			this.vbox7.Add (this.labelDesc);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.labelDesc]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.ebox2.Add (this.vbox7);
			w5.Add (this.ebox2);
			this.scrolledwindow.Add (w5);
			this.vbox3.Add (this.scrolledwindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow]));
			w10.Position = 1;
			this.vbox6.Add (this.vbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox3]));
			w11.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.eboxButs = new global::Gtk.EventBox ();
			this.eboxButs.Name = "eboxButs";
			// Container child eboxButs.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnInstall = new global::Gtk.Button ();
			this.btnInstall.CanFocus = true;
			this.btnInstall.Name = "btnInstall";
			this.btnInstall.UseUnderline = true;
			// Container child btnInstall.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("download.png");
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Install...");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.btnInstall.Add (w12);
			this.hbox1.Add (this.btnInstall);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnInstall]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.CanFocus = true;
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			// Container child btnUpdate.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("download.png");
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Update");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.btnUpdate.Add (w21);
			this.hbox1.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUpdate]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnDisable = new global::Gtk.Button ();
			this.btnDisable.CanFocus = true;
			this.btnDisable.Name = "btnDisable";
			this.btnDisable.UseUnderline = true;
			this.btnDisable.Label = global::Mono.Unix.Catalog.GetString ("Disable");
			this.hbox1.Add (this.btnDisable);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnDisable]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnUninstall = new global::Gtk.Button ();
			this.btnUninstall.CanFocus = true;
			this.btnUninstall.Name = "btnUninstall";
			this.btnUninstall.UseUnderline = true;
			this.btnUninstall.Label = global::Mono.Unix.Catalog.GetString ("_Uninstall...");
			this.hbox1.Add (this.btnUninstall);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUninstall]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.eboxButs.Add (this.hbox1);
			this.vbox6.Add (this.eboxButs);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.eboxButs]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.ebox.Add (this.vbox6);
			this.Add (this.ebox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnInstall.Clicked += new global::System.EventHandler (this.OnBtnInstallClicked);
			this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
			this.btnDisable.Clicked += new global::System.EventHandler (this.OnBtnDisableClicked);
			this.btnUninstall.Clicked += new global::System.EventHandler (this.OnBtnUninstallClicked);
		}
	}
}
