
// This file has been generated by the GUI designer. Do not modify.
namespace Mono.Addins.Gui
{
	internal partial class ErrorDialog
	{
		private global::Gtk.HBox hbox59;
		private global::Gtk.VBox vbox72;
		private global::Gtk.Image icon;
		private global::Gtk.VBox vbox73;
		private global::Gtk.Label descriptionLabel;
		private global::Gtk.Expander expander;
		private global::Gtk.ScrolledWindow scrolledwindow10;
		private global::Gtk.TextView detailsTextView;
		private global::Gtk.Label label102;
		private global::Gtk.Button okButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Mono.Addins.Gui.ErrorDialog
			this.Name = "Mono.Addins.Gui.ErrorDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Error");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.BorderWidth = ((uint)(6));
			// Internal child Mono.Addins.Gui.ErrorDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog-vbox5";
			w1.Spacing = 6;
			// Container child dialog-vbox5.Gtk.Box+BoxChild
			this.hbox59 = new global::Gtk.HBox ();
			this.hbox59.Name = "hbox59";
			this.hbox59.Spacing = 6;
			this.hbox59.BorderWidth = ((uint)(6));
			// Container child hbox59.Gtk.Box+BoxChild
			this.vbox72 = new global::Gtk.VBox ();
			this.vbox72.Name = "vbox72";
			// Container child vbox72.Gtk.Box+BoxChild
			this.icon = new global::Gtk.Image ();
			this.icon.Name = "icon";
			this.icon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Dialog);
			this.vbox72.Add (this.icon);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox72 [this.icon]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox59.Add (this.vbox72);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox59 [this.vbox72]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox59.Gtk.Box+BoxChild
			this.vbox73 = new global::Gtk.VBox ();
			this.vbox73.Name = "vbox73";
			this.vbox73.Spacing = 12;
			// Container child vbox73.Gtk.Box+BoxChild
			this.descriptionLabel = new global::Gtk.Label ();
			this.descriptionLabel.WidthRequest = 540;
			this.descriptionLabel.CanFocus = true;
			this.descriptionLabel.Name = "descriptionLabel";
			this.descriptionLabel.Xalign = 0F;
			this.descriptionLabel.LabelProp = "An exception has been thrown 1 2 3 4 5 6 7 8 9 10 11 12 13 14";
			this.descriptionLabel.Wrap = true;
			this.descriptionLabel.Selectable = true;
			this.vbox73.Add (this.descriptionLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox73 [this.descriptionLabel]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox73.Gtk.Box+BoxChild
			this.expander = new global::Gtk.Expander (null);
			this.expander.CanFocus = true;
			this.expander.Name = "expander";
			// Container child expander.Gtk.Container+ContainerChild
			this.scrolledwindow10 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow10.CanFocus = true;
			this.scrolledwindow10.Name = "scrolledwindow10";
			this.scrolledwindow10.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow10.Gtk.Container+ContainerChild
			this.detailsTextView = new global::Gtk.TextView ();
			this.detailsTextView.HeightRequest = 250;
			this.detailsTextView.CanFocus = true;
			this.detailsTextView.Name = "detailsTextView";
			this.detailsTextView.PixelsAboveLines = 2;
			this.detailsTextView.PixelsBelowLines = 2;
			this.detailsTextView.LeftMargin = 6;
			this.detailsTextView.RightMargin = 6;
			this.scrolledwindow10.Add (this.detailsTextView);
			this.expander.Add (this.scrolledwindow10);
			this.label102 = new global::Gtk.Label ();
			this.label102.Name = "label102";
			this.label102.LabelProp = global::Mono.Unix.Catalog.GetString ("Details");
			this.expander.LabelWidget = this.label102;
			this.vbox73.Add (this.expander);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox73 [this.expander]));
			w7.Position = 1;
			this.hbox59.Add (this.vbox73);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox59 [this.vbox73]));
			w8.Position = 1;
			w1.Add (this.hbox59);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox59]));
			w9.Position = 0;
			// Internal child Mono.Addins.Gui.ErrorDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog-action_area5";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog-action_area5.Gtk.ButtonBox+ButtonBoxChild
			this.okButton = new global::Gtk.Button ();
			this.okButton.CanDefault = true;
			this.okButton.CanFocus = true;
			this.okButton.Name = "okButton";
			this.okButton.UseStock = true;
			this.okButton.UseUnderline = true;
			this.okButton.Label = "gtk-ok";
			this.AddActionWidget (this.okButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.okButton]));
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 632;
			this.DefaultHeight = 155;
			this.Show ();
		}
	}
}
